version: "3.8"
services:
  db:
    image: mongo
    container_name: examen-mongo-db
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      "MONGO_INITDB_ROOT_USERNAME" : "root"
      "MONGO_INITDB_ROOT_PASSWORD" : "password"
volumes:
  data: {}

networks:
  default:
    name: mongodb_network